FROM public.ecr.aws/lambda/python:3.11

# Install runtime dependencies for postgres
# In Amazon Linux 2023, we use dnf/yum with these specific packages
RUN yum install -y postgresql15-devel gcc

# Copy requirements and install
COPY requirements.txt ${LAMBDA_TASK_ROOT}
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . ${LAMBDA_TASK_ROOT}

# Set the handler
CMD [ "handler.handler" ]
